# An input directory containing the files to embed.
input_dir: /home/cucinell/RAG/bvbrc_docs
# An output directory to save the embeddings.
output_dir: /nfs/lambda_stor_01/homes/cucinell/RAG/test_brc_docs
# A set of glob patterns to match the input files.
glob_patterns: ['*.jsonl']

# Settings for reading the input files.
dataset_config:
  name: simple_chunk
  buffer_size: 4
  batch_size: 2

# Settings for the encoder.
encoder_config:
  name: remote_embedding
  server: 140.221.79.23 # lambda13
  port: 9998         
  api_key: AskClark     
  model: Salesforce/SFR-Embedding-Mistral  # The model name running on the remote server
  embedding_size: 4096         # The embedding size of the model
    
# Settings for the pooler.
pooler_config:
  name: last_token

# Settings for the embedder.
embedder_config:
  name: semantic_chunk
  chunk_batch_size: 2
  normalize_embeddings: true

# Settings for the writer.
writer_config:
  name: huggingface

# Settings for the parsl compute backend.
#compute_config:
#  name: workstation
#  available_accelerators: ["0", "1", "2", "3", "4", "5", "6", "7"]
